### ISSUE TITLE
blank viewer page

### ISSUE THREAD

**Issue by lmorfitt** [vincentbernat/serverspec-example#2]
Hello,

when loading the viewer in apache, or rubys http server all i get is a blank page.

Tested in chrome, firefox and safari on OSX.

Any ideas?

thanks

**Comment by vincentbernat** [comment]
❦ 11 juin 2015 02:58 -0700, lmorfitt <notifications@github.com> :

> when loading the viewer in apache, or rubys http server all i get is a
> blank page.
>
> Tested in chrome, firefox and safari on OSX.

Any error in the console?
-- 
Make sure comments and code agree.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by lmorfitt** [comment]
Hello @vincentbernat ,

This has been working for some time, then it stopped.

Seem to be getting 404 on this http://angular-file-upload.appspot.com/js/angular-file-upload.js

thanks,
Luke

**Comment by lmorfitt** [comment]
I've swapped the above URL with http://angular-file-upload.appspot.com/js/ng-file-upload.js and now get the below error.

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.7/$injector/modulerr?p0=reportResultsApp&p1…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js%3A29%3A115)

upon clicking the link i end up here.

https://docs.angularjs.org/error/$injector/modulerr?p0=reportResultsApp&p1=Error:%20%5B$injector:modulerr%5D%20http:%2F%2Ferrors.angularjs.org%2F1.2.7%2F$injector%2Fmodulerr%3Fp0%3DangularFileUpload%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.2.7%252F%2524injector%252Fnomod%253Fp0%253DangularFileUpload%250A%2520%2520%2520%2520at%2520Error%2520(native)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.7%252Fangular.min.js%253A6%253A449%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.7%252Fangular.min.js%253A20%253A260%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.7%252Fangular.min.js%253A21%253A262%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.7%252Fangular.min.js%253A29%253A253%250A%2520%2520%2520%2520at%2520Array.forEach%2520(native)%250A%2520%2520%2520%2520at%2520q%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.7%252Fangular.min.js%253A7%253A274)%250A%2520%2520%2520%2520at%2520e%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.7%252Fangular.min.js%253A29%253A115)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.7%252Fangular.min.js%253A29%253A192%250A%2520%2520%2520%2520at%2520Array.forEach%2520(native)%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js:6:449%0A%20%20%20%20at%20https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js:30:1%0A%20%20%20%20at%20Array.forEach%20(native)%0A%20%20%20%20at%20q%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js:7:274)%0A%20%20%20%20at%20e%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js:29:115)%0A%20%20%20%20at%20https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js:29:192%0A%20%20%20%20at%20Array.forEach%20(native)%0A%20%20%20%20at%20q%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js:7:274)%0A%20%20%20%20at%20e%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.7%2Fangular.min.js:29:115

thanks
Luke

**Comment by lmorfitt** [comment]
@vincentbernat Thank you for a very quick response. Your guide to server spec has really helped.

Thanks!
