### ISSUE TITLE
Errno::EINVAL: Invalid argument - ./reports/spec

### ISSUE THREAD

**Issue by threezerous** [vincentbernat/serverspec-example#4]
Looks like it is unable to instantiate the reports file for some reason. I am using 
ruby 1.9.3p484 and rspec 2.14.8

** Invoke reports:clean
** Execute check:server:all
** Execute spec
** Invoke reports:build (first_time)
** Invoke spec
** Execute reports:build
rake aborted!
Errno::EINVAL: Invalid argument - ./reports/spec--2015-07-07T17:53:07.json
c:/Users/ssonker/cookbooks-downloaded/serverspec-example/Rakefile:160:in `initia
lize'
c:/Users/ssonker/cookbooks-downloaded/serverspec-example/Rakefile:160:in `open'
c:/Users/ssonker/cookbooks-downloaded/serverspec-example/Rakefile:160:in `block
(2 levels) in <top (required)>'

**Comment by vincentbernat** [comment]
I didn't expect people to use Windows. Paths are Unix one. Let me fix that.

**Comment by vincentbernat** [comment]
Could you try with the latest commit? I think it should fix your problem. Reopen if not.

**Comment by threezerous** [comment]
Thanks, will try with latest commitSent from Yahoo Mail for iPhoneAt Jul 8, 2015, 1:14:25 AM, Vincent Bernat wrote:I didn't expect people to use Windows. Paths are Unix one. Let me fix that.

**Comment by threezerous** [comment]
I did not have to use the latest commit. My ruby and bundle versions were outdated. Once I installed ruby 2.1.6 and related devkit, everything went well. Thanks for looking into it.
