### ISSUE TITLE
File upload is broken

### ISSUE THREAD

**Issue by FlxPeters** [vincentbernat/serverspec-example#9]
The Link to http://angular-file-upload.appspot.com/js/angular-file-upload.js isn't valid anymore. 

It seams there is a new Version and the old one is not maintained anymore.

**Comment by vincentbernat** [comment]
Thanks for the port. I'll try to fix this shortly.

**Comment by vincentbernat** [comment]
Do you use the latest version? It has been updated in 9d5c8280c97f5f5f3b55392924ae136796080293.

**Comment by FlxPeters** [comment]
ok, when i clone it, it works. i used the download zip. 

Thanks for this great example!

**Comment by vincentbernat** [comment]
Well, that's odd. Maybe it was a glitch with GitHub (they had trouble yesterday).
